import { type ChildProcessWithoutNullStreams, spawn } from 'child_process';

// Pseudo Code:
// Summon a powershell and enter the command for getting all volume drive letters.
// Gather all the drive letters output by the powershell
// Add all drive letters to an array
// Close the powershell process and return the array of drive letters.

// https://nodejs.org/api/child_process.html#child_processspawncommand-args-options

class PowerShell {
  _shellOutPut: string[];
  _regexExpression: RegExp;
  _isDataAdded: boolean;

  constructor() {
    this._shellOutPut = [];
    this._regexExpression = /[A-Z]/g;
    // Will be used to check if the data generated by the powershell has finished being filtered and added to the output array.
    this._isDataAdded = false;
  }

  //   Initializes the powershell process
  _summonPowerShell(): ChildProcessWithoutNullStreams {
    const process = spawn('powershell.exe', ['(Get-Volume).DriveLetter']);
    return process;
  }

  _checkIsDataAdded(): Promise<boolean> {
    return new Promise((resolve, reject) => {
      try {
        const checkInterval = setInterval(() => {
          if (this._isDataAdded === true) {
            checkInterval.close();
            resolve(true);
            return;
          }
        }, 250);
      } catch (error) {
        console.error(error);
        reject(error);
      }
    });
  }

  //   Filters the passed in string of the Capitalized characters
  _filterUserDrives(data: string): void {
    const userDrives = data.matchAll(this._regexExpression);
    userDrives.forEach((drive) => {
      this._shellOutPut.push(drive.toString());
    });
    this._isDataAdded = true;
  }

  //   Handles the closing of the powershell process, returns true if the process closes correctly or throws an error if the process fails to close properly.
  _handleClosing(code: number | null): boolean {
    if (code !== 0) {
      throw new Error(`Exited with error code ${code}!`);
    } else {
      //   console.log('close');
      return true;
    }
  }

  //   Queries powershell to gather all of the user's drives available on their system,
  //    Returns a promise that resolves with the powershell output data, and rejects with the error that caused the failure.
  async getUserDrives(): Promise<string[]> {
    // Sets the data indictor boolean to false
    this._isDataAdded = false;

    return new Promise((resolve, reject) => {
      try {
        const process = this._summonPowerShell();

        process.stdout.on('data', (data) => {
          // Converts the returned data to a string and passes it to the filter method.
          this._filterUserDrives(data.toString('utf8'));
        });

        process.on('close', async (code) => {
          // Halts the process until the data is finished being added to the array
          await this._checkIsDataAdded();
          const isClosed = this._handleClosing(code);
          if (isClosed) resolve(this._shellOutPut);
        });
      } catch (error) {
        console.error(error);
        reject(error);
      }
    });
  }
}

export async function pullUserDrives(): Promise<string[]> {
  try {
    const newShell = new PowerShell();
    const userDrives = await newShell.getUserDrives();
    return userDrives;
  } catch (error) {
    console.error(error);
    return [];
  }
}
